name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lftp openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SFTP
        run: |
          LOCALDIR=$(pwd)
          REMOTEDIR="${{ secrets.REMOTE_PROD_PROJECT_FOLDER_PATH }}"

          lftp sftp://${{ secrets.SFTP_PROD_USERNAME }}:${{ secrets.SFTP_PROD_PWD }}@${{ secrets.REMOTE_HOST }} -e "
            set sftp:auto-confirm yes;
            set net:timeout 300;
            set net:max-retries 3;
            cd $REMOTEDIR;
            mirror -R -v --only-newer --delete \
              --exclude dist/ \
              --exclude .git/ \
              --exclude .github/ \
              --exclude github/ \
              --exclude node_modules/ \
              $LOCALDIR/ ./
            quit
          "

      - name: Remote SSH - Install, Build and Restart
        run: |
          SSH_USER=${{ secrets.SFTP_PROD_USERNAME }}
          SSH_HOST=${{ secrets.REMOTE_HOST }}
          APP_DIR=${{ secrets.REMOTE_PROD_PROJECT_FOLDER_PATH }}

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            cd "$APP_DIR"
            npm install
            npm run build
          EOF
